package io.velo.was.admin.cli;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ScriptRecorder {

    private final Path scriptFile;
    private final List<String> commands = new ArrayList<>();

    public ScriptRecorder(Path scriptFile) {
        this.scriptFile = scriptFile;
    }

    public void record(String command) {
        if (command != null && !command.isBlank()) {
            commands.add(command.trim());
        }
    }

    public List<String> commands() {
        return Collections.unmodifiableList(commands);
    }

    public void close() {
        try (BufferedWriter writer = Files.newBufferedWriter(scriptFile, StandardCharsets.UTF_8)) {
            writer.write("# Velo WAS Admin CLI Script");
            writer.newLine();
            writer.write("# Generated by veloadmin record-script");
            writer.newLine();
            writer.newLine();
            for (String command : commands) {
                writer.write(command);
                writer.newLine();
            }
        } catch (IOException e) {
            throw new RuntimeException("Failed to save script: " + scriptFile, e);
        }
    }
}
